# Generated by Django 4.2.30 on 2026-05-02 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], max_length=10)),
                ('source', models.CharField(choices=[('order_payment', 'Paiement commande'), ('refund', 'Remboursement'), ('cashback', 'Cashback promo'), ('earning', 'Gain livraison'), ('withdrawal', 'Retrait'), ('top_up', 'Rechargement'), ('commission', 'Commission plateforme')], default='order_payment', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction de wallet',
                'verbose_name_plural': 'Transactions de wallet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic — Gratuit'), ('pro', 'Pro — 5000 XOF/mois'), ('enterprise', 'Enterprise — 15000 XOF/mois')], default='basic', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('renewed_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='stores.store')),
            ],
            options={
                'verbose_name': 'Abonnement boutique',
                'verbose_name_plural': 'Abonnements boutiques',
            },
        ),
        migrations.CreateModel(
            name='StoreSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='weekly', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Montant brut des ventes', max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Commission plateforme', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Montant net reversé', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('paid', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='stores.store')),
            ],
            options={
                'verbose_name': 'Reversement boutique',
                'verbose_name_plural': 'Reversements boutiques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('commission', 'Commission commande'), ('delivery_fee', 'Frais de livraison'), ('ad', 'Publicité boutique'), ('subscription', 'Abonnement premium'), ('penalty', 'Pénalité')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_revenues', to='orders.order')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_revenues', to='stores.store')),
            ],
            options={
                'verbose_name': 'Revenu plateforme',
                'verbose_name_plural': 'Revenus plateforme',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Carte bancaire'), ('cod', 'Cash à la livraison'), ('wallet', 'Wallet interne')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=140)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
