# Generated by Django 4.2.30 on 2026-05-02 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assignée'), ('accepted', 'Acceptée'), ('picking_up', 'En route vers boutique'), ('picked_up', 'Colis récupéré'), ('on_route', 'En route vers client'), ('delivered', 'Livrée'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], default='assigned', max_length=20)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('driver_earning', models.DecimalField(decimal_places=2, default=0, help_text='Gain du livreur pour cette mission en XOF', max_digits=10)),
                ('proof_photo_url', models.URLField(blank=True, help_text='Photo de remise de la commande')),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('signature_data', models.TextField(blank=True, help_text='Signature numérique encodée base64')),
                ('estimated_duration', models.PositiveIntegerField(default=0, help_text='Durée estimée en minutes')),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='users.userprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_mission', to='orders.order')),
            ],
            options={
                'verbose_name': 'Mission de livraison',
                'verbose_name_plural': 'Missions de livraison',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
