# Generated by Django 4.2.30 on 2026-05-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='momo_number',
            field=models.CharField(blank=True, help_text='Numéro pour recevoir les paiements', max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='momo_type',
            field=models.CharField(choices=[('orange', 'Orange Money'), ('moov', 'Moov Money')], default='orange', max_length=20),
        ),
    ]
