# Generated by Django 4.2.30 on 2026-05-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_deliverer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_otp',
            field=models.CharField(blank=True, help_text='Code OTP pour valider le paiement', max_length=6),
        ),
    ]
