# Generated by Django 4.2.30 on 2026-05-02 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modèle de notification',
                'verbose_name_plural': 'Modèles de notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('order_received', 'Commande reçue'), ('order_confirmed', 'Commande confirmée'), ('order_cancelled', 'Commande annulée'), ('preparing', 'En préparation'), ('order_ready', 'Commande prête'), ('payment_validated', 'Paiement validé'), ('driver_assigned', 'Livreur assigné'), ('driver_en_route', 'Livreur en route'), ('picked_up', 'Colis récupéré'), ('delivered', 'Livrée'), ('delivery_failed', 'Livraison échouée'), ('new_mission', 'Nouvelle mission'), ('mission_cancelled', 'Mission annulée'), ('earning_credited', 'Gain crédité'), ('pickup_ready', 'Prêt à récupérer'), ('new_order', 'Nouvelle commande'), ('payment_received', 'Paiement reçu'), ('settlement_ready', 'Reversement prêt'), ('info', 'Information'), ('promo', 'Promotion'), ('bonus', 'Bonus')], default='info', max_length=30)),
                ('channel', models.CharField(choices=[('inapp', 'In-App'), ('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification')], default='inapp', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
