# Generated by Django 4.2.30 on 2026-05-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount_price_product_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, help_text='Ex: Rouge, #FF0000', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, help_text='Ex: XL, 42, 128GB', max_length=50, null=True),
        ),
    ]
